### ISSUE TITLE
information loss during obstacle pipeline

### ISSUE THREAD

**Issue by wentscher** [bit-bots/humanoid_league_msgs#2]
It seems that there is an information loss during the chain. In the ObstacleInImage.msg [line 21-22](https://github.com/bit-bots/humanoid_league_msgs/blob/d9de43d56bd3189974c828800a264a1d658886d5/msg/ObstacleInImage.msg#L21-L22) there is the height and the width of the obstacle specified but in ObstacleRelative.msg [line 22-33](https://github.com/bit-bots/humanoid_league_msgs/blob/d9de43d56bd3189974c828800a264a1d658886d5/msg/ObstacleRelative.msg#L22-L23) just the width remains.
I would suggest to add the height also to the msg

**Comment by SammyRamone** [comment]
Hi,
sorry for the late reply.
It is not easy to get the actual height in relative space from the height in image space, for example if the object is not standing straight, but you're right never the less.
I added the height value.
Thank you veryy much for your contribution
