### ISSUE TITLE
Kick Action is not built

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_msgs#24]
# Kick Action is not built

## Expected behavior

Either the kick action does not exist or is built.

## Current behavior

The kick action exists but is not built
Is this intentional?

**Comment by timonegk** [comment]
We use [the KickAction from bitbots_msgs](https://github.com/bit-bots/bitbots_msgs/blob/master/action/Kick.action), not this one. This one does not even compile because it is not a valid action (does not consist of three parts). I think we should just delete it.
