### ISSUE TITLE
Inconsistencies in variable names

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_msgs#4]
There are inconsistencies in variable names in some of the messages:
Position of a BallRelative: ball_relative
Position of an ObstacleRelative: position

I don't know whether we should change this or not. It has the potential to break a LOT if we change it. But it isn't pretty either...

**Comment by SammyRamone** [comment]
maybe change this after this years RoboCup?

**Comment by SammyRamone** [comment]
So now is after RoboCup so lets discuss what we want to change. I have found the following points:
1. confidence for detected balls, etc. is given as a float value. Do we want to change this to a coveriance matrix? Can still encode the same information if the float is put in as a identity matrix 
2. Position variables should only be named "position" (e.g. in BallRelative)
3. There is no FieldBoundaryRelative message
4. The goal detection messages are still quite confusing and do not fit for all detection approaches well (e.g. having something yolo like which detect full goals)

**Comment by SammyRamone** [comment]
https://github.com/bit-bots/humanoid_league_msgs/pull/14
