### ISSUE TITLE
Usages deprecated message type Pose2D

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_msgs#5]
In the [documentation](https://docs.ros.org/api/geometry_msgs/html/msg/Pose2D.html), Pose2D is marked as "deprecated". It is used in this package. 
I'd suppose, we switch to the Pose message. It is WAY easier to transform!

**Comment by SammyRamone** [comment]
good point!
but we should only do interface changes after this years robocup

**Comment by SammyRamone** [comment]
https://github.com/bit-bots/humanoid_league_msgs/pull/14
