### ISSUE TITLE
Association of detections in the TeamData message do not work

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_msgs#7]
As detections in the TeamData message are relative to the detecting robot, it is crucial to associate to be able to associate each robot with its detections in the message. In the current version of the TeamData message, the association is done by using the same index in multiple lists of detections for each teammate. This breaks because we can not use a placeholder in case we do not detect something.

**Example**: 
robot_1 detects 3 opponents. Opponent_d is still empty. When robot_2 detects 4 opponents, the fourth detection will be associated with robot_1. 
We can not sort the list of robots by the amount of opponent detections, because then, we might break stuff in the mate detection.

**Workaround**:
As a temporary workaround, I propose to use a dummy detection with extremely high position values (e.g. (1000, 1000, 1000)) which get filtered at the receiving end.

**Comment by SammyRamone** [comment]
https://github.com/bit-bots/humanoid_league_msgs/pull/14
