### ISSUE TITLE
Goal in Image is unnecessary

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_msgs#8]
In my opinion, the message GoalInImage is unnecessary, because it is way easier to classify valid goalposts in Cartesian space (as we could use their distance to each other etc.) thus, it would be best to transform GoalPartsInImage into cartesian space and decide afterward, how the parts fit together.

**Comment by lilioid** [comment]
Closed because other teams might use an algorithm which detects the whole goal. Therefore the message is not completely unnecessary but just not used by us
