### ISSUE TITLE
GameState: Add states introduced for RoboCup 2019

### ISSUE THREAD

**Issue by timonegk** [bit-bots/humanoid_league_msgs#9]
From the email:

* Three new 'state2' have been introduced 
(CornerKick:7,GoalKick:8,ThrowIn:9).

* All game Interruption are now using the following procedure:

    1. Preparation phase: All robot shoulds stop moving, ball is being 
placed (FreeKickInfo = 0)

    2. Placing phase: Robots can position themselves (FreeKickInfo = 1)

    3. End phase: Illegally positioned robots are removed from the field 
(FreeKickInfo = 2)

**Comment by Flova** [comment]
I thought we are correctly handling these states already. Weird.

**Comment by Flova** [comment]
The issue is also in done and there is a merged pr
